name: Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write 

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_DEFAULT_REGION: ap-southeast-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::960468475092:role/OIDCDeploymentEKS
          aws-region: ap-southeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Terraform Init
        run: terraform init
        working-directory: tf-eks

      - name: Terraform Validate
        run: terraform validate
        working-directory: tf-eks

      - name: Terraform Apply
        run: terraform apply --var-file="variables/terraform.tfvars" -auto-approve
        working-directory: tf-eks

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name eks-cluster

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f nginx-deployment.yaml
        working-directory: kubernetes

      - name: Apply Kubernetes Service
        run: kubectl apply -f nginx-service.yaml
        working-directory: kubernetes
