name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_DEFAULT_REGION: ap-southeast-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Terraform Init
        run: terraform init
        working-directory: tf-eks

      - name: Terraform Validate
        run: terraform validate
        working-directory: tf-eks

      - name: Terraform Apply
        run: terraform apply --var-file="variables/terraform.tfvars" -auto-approve
        working-directory: tf-eks

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name eks-cluster

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f nginx-deployment.yaml
        working-directory: kubernetes

      - name: Apply Kubernetes Service
        run: kubectl apply -f nginx-service.yaml
        working-directory: kubernetes
